from __future__ import annotations

import argparse
import concurrent.futures as cf
import hashlib
import json
import random
import sys
import threading
import time
import urllib.parse
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

import requests

import collect_corpus as base

INNERTUBE_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"
INNERTUBE_CLIENTS: tuple[dict[str, Any], ...] = (
    {"clientName": "ANDROID", "clientVersion": "20.10.38", "androidSdkVersion": 30, "hl": "ko", "gl": "KR"},
    {"clientName": "TVHTML5", "clientVersion": "7.20250316", "hl": "ko", "gl": "KR"},
    {"clientName": "WEB", "clientVersion": "2.20250721.00.00", "hl": "ko", "gl": "KR"},
)
LANG_PRIORITY = base.LANG_PRIORITY
_INSTANCE_LOCK = threading.Lock()
_PIPED_INSTANCES: list[str] | None = None
_INVIDIOUS_INSTANCES: list[str] | None = None


def headers() -> dict[str, str]:
    return {
        "User-Agent": (
            "Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/124.0 Mobile Safari/537.36"
        ),
        "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.7,en;q=0.5",
        "Accept": "application/json,text/plain,*/*",
    }


def parse_response(response: requests.Response) -> list[dict[str, Any]]:
    if not response.content:
        return []
    text = response.text
    content_type = response.headers.get("content-type", "").lower()
    try:
        if "json" in content_type or text.lstrip().startswith("{"):
            return base.parse_json3(response.json())
        if text.lstrip().startswith("WEBVTT"):
            return base.parse_vtt(text)
        return base.parse_xmlish(text)
    except Exception:
        return []


def language_code(track: dict[str, Any]) -> str:
    return str(
        track.get("languageCode")
        or track.get("lang_code")
        or track.get("lang")
        or track.get("code")
        or ""
    )


def rank_tracks(tracks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    def score(track: dict[str, Any]) -> tuple[int, int, str]:
        language = language_code(track)
        if language in LANG_PRIORITY:
            language_rank = LANG_PRIORITY.index(language)
        elif language.startswith("ko"):
            language_rank = len(LANG_PRIORITY)
        elif language.startswith("en"):
            language_rank = len(LANG_PRIORITY) + 1
        else:
            language_rank = len(LANG_PRIORITY) + 2
        automatic = bool(track.get("autoGenerated")) or str(track.get("kind") or "") == "asr"
        return language_rank, int(automatic), language

    return sorted([track for track in tracks if isinstance(track, dict)], key=score)


def fetch_track(session: requests.Session, url: str) -> list[dict[str, Any]]:
    separator = "&" if "?" in url else "?"
    candidates = [f"{url}{separator}fmt=json3", url]
    for candidate in candidates:
        try:
            response = session.get(candidate, timeout=40)
            response.raise_for_status()
            segments = parse_response(response)
            if segments:
                return segments
        except Exception:
            continue
    return []


def from_innertube(video_id: str) -> tuple[list[dict[str, Any]], str, str, str] | None:
    endpoint = f"https://www.youtube.com/youtubei/v1/player?key={INNERTUBE_KEY}&prettyPrint=false"
    session = requests.Session()
    session.headers.update(headers())
    for client in INNERTUBE_CLIENTS:
        try:
            response = session.post(
                endpoint,
                json={
                    "context": {"client": client},
                    "videoId": video_id,
                    "contentCheckOk": True,
                    "racyCheckOk": True,
                },
                timeout=35,
            )
            response.raise_for_status()
            data = response.json()
            tracks = (
                data.get("captions", {})
                .get("playerCaptionsTracklistRenderer", {})
                .get("captionTracks", [])
            )
            for track in rank_tracks(tracks):
                url = str(track.get("baseUrl") or "")
                if not url:
                    continue
                segments = fetch_track(session, url)
                if segments:
                    kind = str(track.get("kind") or ("asr" if track.get("isTranslatable") else "manual"))
                    return segments, f"youtube-innertube:{client['clientName']}", language_code(track) or "unknown", kind
        except Exception:
            continue
    return None


def from_timedtext(video_id: str) -> tuple[list[dict[str, Any]], str, str, str] | None:
    hosts = (
        "https://www.youtube.com/api/timedtext",
        "https://video.google.com/timedtext",
        "https://www.youtube-nocookie.com/api/timedtext",
    )
    session = requests.Session()
    session.headers.update(headers())
    requests_to_try: list[tuple[str, dict[str, str]]] = []
    for host in hosts:
        try:
            listing = session.get(host, params={"type": "list", "v": video_id, "hl": "ko"}, timeout=20)
            listing.raise_for_status()
            if listing.text.strip():
                root = ET.fromstring(listing.text)
                tracks = [dict(node.attrib) for node in root.iter() if node.tag.rsplit("}", 1)[-1] == "track"]
                for track in rank_tracks(tracks):
                    params = {
                        "v": video_id,
                        "lang": track.get("lang_code") or track.get("lang") or "ko",
                        "fmt": "json3",
                    }
                    if track.get("kind"):
                        params["kind"] = str(track["kind"])
                    if track.get("name"):
                        params["name"] = str(track["name"])
                    requests_to_try.append((host, params))
        except Exception:
            pass
        for language in ("ko", "ko-KR", "en"):
            requests_to_try.append((host, {"v": video_id, "lang": language, "fmt": "json3"}))
            requests_to_try.append((host, {"v": video_id, "lang": language, "kind": "asr", "fmt": "json3"}))
    seen: set[str] = set()
    for host, params in requests_to_try:
        marker = host + "?" + urllib.parse.urlencode(sorted(params.items()))
        if marker in seen:
            continue
        seen.add(marker)
        try:
            response = session.get(host, params=params, timeout=25)
            response.raise_for_status()
            segments = parse_response(response)
            if segments:
                return segments, "youtube-direct-timedtext", params.get("lang", "unknown"), params.get("kind", "manual")
        except Exception:
            continue
    return None


def piped_instances() -> list[str]:
    global _PIPED_INSTANCES
    with _INSTANCE_LOCK:
        if _PIPED_INSTANCES is not None:
            return _PIPED_INSTANCES
        instances = [
            "https://pipedapi.adminforge.de",
            "https://pipedapi.reallyaweso.me",
            "https://pipedapi.kavin.rocks",
            "https://pipedapi.leptons.xyz",
        ]
        try:
            response = requests.get("https://piped.video/api/v1/instances", headers=headers(), timeout=25)
            response.raise_for_status()
            payload = response.json()
            for item in payload:
                api_url = item.get("api_url") if isinstance(item, dict) else None
                if api_url and str(api_url).startswith("https://"):
                    instances.append(str(api_url).rstrip("/"))
        except Exception:
            pass
        _PIPED_INSTANCES = list(dict.fromkeys(instances))[:20]
        return _PIPED_INSTANCES


def from_piped(video_id: str) -> tuple[list[dict[str, Any]], str, str, str] | None:
    session = requests.Session()
    session.headers.update(headers())
    for instance in piped_instances():
        try:
            response = session.get(f"{instance}/streams/{video_id}", timeout=30)
            response.raise_for_status()
            payload = response.json()
            tracks = payload.get("subtitles") or []
            for track in rank_tracks(tracks):
                url = str(track.get("url") or "")
                if url.startswith("/"):
                    url = instance + url
                if not url:
                    continue
                segments = fetch_track(session, url)
                if segments:
                    kind = "asr" if track.get("autoGenerated") else "manual"
                    return segments, f"piped:{instance}", language_code(track) or "unknown", kind
        except Exception:
            continue
    return None


def invidious_instances() -> list[str]:
    global _INVIDIOUS_INSTANCES
    with _INSTANCE_LOCK:
        if _INVIDIOUS_INSTANCES is not None:
            return _INVIDIOUS_INSTANCES
        instances = ["https://yewtu.be", "https://invidious.privacyredirect.com", "https://inv.nadeko.net"]
        try:
            response = requests.get("https://api.invidious.io/instances.json", headers=headers(), timeout=25)
            response.raise_for_status()
            for host, metadata in response.json():
                details = metadata.get("details") if isinstance(metadata, dict) else None
                if isinstance(details, dict) and details.get("api") and details.get("type") == "https":
                    instances.append(f"https://{host}")
        except Exception:
            pass
        _INVIDIOUS_INSTANCES = list(dict.fromkeys(instances))[:20]
        return _INVIDIOUS_INSTANCES


def from_invidious(video_id: str) -> tuple[list[dict[str, Any]], str, str, str] | None:
    session = requests.Session()
    session.headers.update(headers())
    for instance in invidious_instances():
        endpoint = f"{instance}/api/v1/captions/{video_id}"
        try:
            response = session.get(endpoint, timeout=30)
            response.raise_for_status()
            payload = response.json()
            tracks = payload.get("captions") or payload if isinstance(payload, list) else []
            for track in rank_tracks(tracks):
                url = str(track.get("url") or "")
                if url.startswith("/"):
                    url = instance + url
                segments: list[dict[str, Any]] = []
                if url:
                    segments = fetch_track(session, url)
                if not segments and track.get("label"):
                    caption_response = session.get(endpoint, params={"label": track["label"]}, timeout=30)
                    caption_response.raise_for_status()
                    segments = parse_response(caption_response)
                if segments:
                    return segments, f"invidious:{instance}", language_code(track) or "unknown", "manual"
        except Exception:
            continue
    return None


def from_transcript_api(video_id: str) -> tuple[list[dict[str, Any]], str, str, str] | None:
    result = base.transcript_api_fallback(video_id)
    if result is None:
        return None
    segments, source = result
    return segments, source, "unknown", "fallback"


def save_transcript(record: base.VideoRecord, output_root: Path, result: tuple[list[dict[str, Any]], str, str, str]) -> base.VideoRecord:
    segments, source, language, kind = result
    clean: list[dict[str, Any]] = []
    for item in segments:
        text = base.normalized_text(str(item.get("text") or ""))
        if text:
            clean.append(
                {
                    "start": round(float(item.get("start") or 0.0), 3),
                    "duration": round(max(0.0, float(item.get("duration") or 0.0)), 3),
                    "text": text,
                }
            )
    text = "\n".join(item["text"] for item in clean).strip()
    if not text:
        record.transcript_status = "missing"
        record.error = "all caption methods parsed to empty text"
        return record
    channel_dir = output_root / "transcripts" / record.channel_key
    channel_dir.mkdir(parents=True, exist_ok=True)
    json_path = channel_dir / f"{record.video_id}.json"
    txt_path = channel_dir / f"{record.video_id}.txt"
    payload = {
        "schema_version": 2,
        "channel_key": record.channel_key,
        "channel_name": record.channel_name,
        "video_id": record.video_id,
        "title": record.title,
        "webpage_url": record.webpage_url,
        "upload_date": record.upload_date,
        "duration_seconds": record.duration_seconds,
        "source": source,
        "language": language,
        "kind": kind,
        "segments": clean,
    }
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    txt_path.write_text(text + "\n", encoding="utf-8")
    record.transcript_status = "ok"
    record.transcript_source = source
    record.transcript_language = language
    record.transcript_kind = kind
    record.transcript_segments = len(clean)
    record.transcript_characters = len(text)
    record.transcript_sha256 = hashlib.sha256(text.encode("utf-8")).hexdigest()
    record.transcript_path = str(txt_path.relative_to(output_root))
    return record


def process(record: base.VideoRecord, output_root: Path) -> base.VideoRecord:
    time.sleep(random.uniform(0.05, 0.3))
    methods = (from_innertube, from_timedtext, from_transcript_api, from_piped, from_invidious)
    errors: list[str] = []
    for method in methods:
        try:
            result = method(record.video_id)
            if result is not None:
                return save_transcript(record, output_root, result)
        except Exception as exc:
            errors.append(f"{method.__name__} {type(exc).__name__}: {exc}")
    record.transcript_status = "missing"
    record.error = "; ".join(errors) or "no public caption returned by five independent methods"
    return record


def self_test() -> None:
    base.self_test()
    assert language_code({"languageCode": "ko"}) == "ko"
    assert rank_tracks([{"languageCode": "en"}, {"languageCode": "ko"}])[0]["languageCode"] == "ko"
    print("v2 self-test: ok")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Resilient complete YouTube caption collector.")
    parser.add_argument("--output", type=Path, default=Path("artifact/corpus"))
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.self_test:
        self_test()
        return 0
    started_at = base.utc_now()
    output: Path = args.output
    output.mkdir(parents=True, exist_ok=True)
    enumerated: list[base.VideoRecord] = []
    enumeration_errors: list[dict[str, str]] = []
    for channel in base.CHANNELS:
        for tab in base.TAB_NAMES:
            try:
                enumerated.extend(base.enumerate_tab(channel, tab))
            except Exception as exc:
                enumeration_errors.append(
                    {
                        "channel_key": channel["channel_key"],
                        "channel_name": channel["display_name"],
                        "tab": tab,
                        "error": f"{type(exc).__name__}: {exc}",
                    }
                )
    records = base.merge_records(enumerated)
    if args.limit > 0:
        records = [
            record
            for channel in base.CHANNELS
            for record in [item for item in records if item.channel_key == channel["channel_key"]][-args.limit :]
        ]
    (output / "ENUMERATION_ERRORS.json").write_text(
        json.dumps(enumeration_errors, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"[{base.utc_now()}] v2 unique videos: {len(records)}", flush=True)
    processed: list[base.VideoRecord] = []
    with cf.ThreadPoolExecutor(max_workers=max(1, min(args.workers, 6))) as executor:
        futures = {executor.submit(process, record, output): record for record in records}
        for index, future in enumerate(cf.as_completed(futures), start=1):
            result = future.result()
            processed.append(result)
            print(
                f"[{base.utc_now()}] {index}/{len(records)} {result.channel_name} {result.video_id} "
                f"{result.transcript_status} source={result.transcript_source} chars={result.transcript_characters} {result.title[:80]}",
                flush=True,
            )
    processed.sort(key=lambda item: (item.channel_key, item.timestamp or 0, item.upload_date or "", item.video_id))
    summary = base.write_outputs(processed, output, started_at)
    summary["collector_version"] = 2
    (output / "CORPUS_SUMMARY.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True), flush=True)
    return 3 if enumeration_errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
